dist: focal
language: ruby
addons:
  postgresql: "13"
  apt:
    packages:
      - postgresql-13
env:
  global:
    - PGUSER=postgres
    - PGPORT=5432
    - PGHOST=localhost
before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - curl 'https://api.rollbar.com/api/1/status/ping'
  - cat rollbar.sh
  - sleep 2
  - postgres --version
before_script:
  - gem install bundler
script:
  - psql -c 'create database freecouches;' -U postgres 
